language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yomarguti/weather-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yomarguti/weather-react npm run test
