language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yomarguti/weather-react -f Dockerfile.dev .

# e variables de entorno
# CI=true => testwatch false
script:
  - docker run -e CI=true yomarguti/weather-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'weather-react-docker'
  env: 'WeatherReactDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-636262017077'
  bucket_path: 'weather-react-docker'
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
